const guardLines = [
  `Move along, nothing to see here.`,
  `Well, this is a nice mess you've gotten me into.`,
  `I catch you stealing anything, I will break your neck.`,
  `By the order of the Jarl, stop right there!`,
  `Stay away from that.`,
  `You have commited crimes against Skyrim and her people, what say you in your defense?`,
  `Oh, forgive me, Thane, I didn't realize it was you.`,
  `Put that down.`,
  `Get away from me.`,
  `Not my problem.`,
  `A little coin always greases the wheels.`,
  `Good dog.`,
  `Stupid dog.`,
  `Guard might get nervous, a woman approaches with her weapon drawn.`,
  `You come up to me, fists raised. You looking for a beating?`,
  `Iron sword, huh? What are you killing, butterflies?`,
  `Everything's alright?`,
  `Trouble?`,
  `Staying safe, I hope?`,
  `I mostly deal with petty thievery and drunken brawls. Been too long since we had a good bandit raid.`,
  `That is one big hammer.`,
  `What a foul and unnatural weapon you wield. Never have I seen its like.`,
  ``,
  ``,
  ``,
  ``,
  ``,
  ``,
  ``,
  ``,
  ``,


];

export default guardLines;